<a href="https://colab.research.google.com/github/Harsh-Yadav-02/PyTorch_00/blob/main/00_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])

TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

## Random Tensors


## Random Tensors
`Sart with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [22]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[8.0740e-01, 1.6712e-01, 9.0623e-01, 8.6006e-01],
         [3.2491e-01, 3.5594e-01, 7.5662e-04, 7.7454e-02],
         [9.5534e-01, 2.4826e-01, 6.1593e-01, 3.6422e-01]],

        [[3.0453e-01, 8.9478e-03, 5.1036e-01, 1.0253e-01],
         [4.5770e-01, 7.4187e-01, 8.2729e-01, 5.3108e-01],
         [6.3606e-01, 3.8867e-01, 7.6689e-01, 8.4010e-02]]])

In [23]:
random_tensor.ndim

3

In [24]:
random_tensor.shape

torch.Size([2, 3, 4])

In [25]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeroes and Ones

In [26]:
# Create a tensor of all zeroes
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [29]:
# Create a tensor of all Ones
ones = torch.ones(3,4
)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

In [32]:
ones*random_tensor

tensor([[[8.0740e-01, 1.6712e-01, 9.0623e-01, 8.6006e-01],
         [3.2491e-01, 3.5594e-01, 7.5662e-04, 7.7454e-02],
         [9.5534e-01, 2.4826e-01, 6.1593e-01, 3.6422e-01]],

        [[3.0453e-01, 8.9478e-03, 5.1036e-01, 1.0253e-01],
         [4.5770e-01, 7.4187e-01, 8.2729e-01, 5.3108e-01],
         [6.3606e-01, 3.8867e-01, 7.6689e-01, 8.4010e-02]]])

### Create a range of tensors

In [38]:
one_to_ten = torch.arange(1, 11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##  Tensors Datatypes

Tensor operations include
* Addition
* Substraction
* Multipliication_element-wise
* Division
* Matrix Multiplication

In [40]:
# create a tensor
tensor = torch .tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [41]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [42]:
# subtract
tensor - 10

tensor([-9, -8, -7])

In [43]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication


Two main ways of performing multiplcation in neural networks  and deep learning:
1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

In [46]:
#  Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]

print(value)


tensor(14)
CPU times: user 587 µs, sys: 0 ns, total: 587 µs
Wall time: 595 µs


In [52]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 932 µs, sys: 0 ns, total: 932 µs
Wall time: 940 µs


tensor(14)

In [55]:
tensor_1 = torch.rand(3, 2)
tensor_2 = torch.rand(3, 2)
tensor_1, tensor_2

(tensor([[0.2082, 0.8173],
         [0.0887, 0.6811],
         [0.5029, 0.5834]]),
 tensor([[0.2324, 0.6054],
         [0.9190, 0.8278],
         [0.5380, 0.5972]]))

In [56]:
torch.mm(tensor_1, tensor_2)

RuntimeError: ignored

# To fix tensor issues, we can manipulate the shape of one of our tensors using a **Transpose**.

A **transpose** switches the axis or dimensions of a given tensor

In [58]:
tensor_2.T

tensor([[0.2324, 0.9190, 0.5380],
        [0.6054, 0.8278, 0.5972]])

In [59]:
torch.mm(tensor_1, tensor_2.T)

tensor([[0.5432, 0.8679, 0.6002],
        [0.4330, 0.6454, 0.4546],
        [0.4701, 0.9451, 0.6190]])